const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const event=()=>({listeners:[],addListener(fn){this.listeners.push(fn);}});
const chrome={debugger:{onEvent:event(),onDetach:event(),attach:async()=>{},detach:async()=>{},sendCommand:async()=>({data:"test"})},tabs:{onRemoved:event(),onUpdated:event(),query:async()=>[{id:1,url:'https://site.test/page'}],captureVisibleTab:async()=> 'data:image/png;base64,test'},runtime:{onMessage:event()}};
const context=vm.createContext({chrome,URL,Date,Map,setTimeout,clearTimeout});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../diagnostics-worker.js'),'utf8'),context);
const command=(type,tab=1)=>context.diagnosticCommand({type,viewport:{x:0,y:0,width:1200,height:900}},{frameId:0,tab:{id:tab,windowId:1,url:'https://site.test/page'}});
const emit=(name,data,tab=1)=>chrome.debugger.onEvent.listeners[0]({tabId:tab},name,data);
(async()=>{
  await command('DIAGNOSTICS_START');
  emit('Runtime.consoleAPICalled',{type:'error',args:[{type:'string',value:'password=abc email=a@b.com https://site.test/api?token=secret#x'}]});
  emit('Runtime.consoleAPICalled',{type:'error',args:[{type:'string',value:'other tab'}]},2);
  emit('Network.requestWillBeSent',{requestId:'1',request:{url:'https://user:pwd@site.test/api?token=secret',method:'POST',postData:'PRIVATE'},timestamp:10,type:'Fetch'});
  emit('Network.responseReceived',{requestId:'1',response:{status:500,headers:{secret:'PRIVATE'}},type:'Fetch'});
  emit('Network.loadingFinished',{requestId:'1',timestamp:10.25});
  let data=await command('DIAGNOSTICS_GET');
  assert.equal(data.errors.length,1);assert.equal(data.requests[0].durationMs,250);assert.equal(data.requests[0].status,500);
  assert.equal(data.requests[0].url,'https://site.test/api');
  const serialized=JSON.stringify(data);for(const secret of ['abc','a@b.com','token=secret','PRIVATE','user:pwd'])assert(!serialized.includes(secret));
  await command('DIAGNOSTICS_STOP');emit('Runtime.consoleAPICalled',{type:'error',args:[{type:'string',value:'stopped'}]});
  assert.equal((await command('DIAGNOSTICS_GET')).errors.length,1);
  await command('DIAGNOSTICS_START');for(let i=0;i<105;i++)emit('Network.requestWillBeSent',{requestId:String(i),request:{url:'https://site.test/api',method:'GET'},timestamp:10});
  data=await command('DIAGNOSTICS_GET');assert.equal(data.requests.length,100);assert.equal(data.dropped,5);
  chrome.tabs.onUpdated.listeners[0](1,{url:'https://other.test/'});assert.equal((await command('DIAGNOSTICS_GET')).recording,false);
  assert.equal((await command('CAPTURE_FEEDBACK')).dataUrl,'data:image/png;base64,test');
  await assert.rejects(command('CAPTURE_FEEDBACK',2));
  await command('DIAGNOSTICS_CLEAR');assert.equal((await command('DIAGNOSTICS_GET')).requests.length,0);
  let detached=false;chrome.debugger.attach=async()=>{throw Error('Occupied')};chrome.debugger.detach=async()=>{detached=true;};
  await assert.rejects(command('DIAGNOSTICS_START'));assert(!detached);
  console.log('Diagnostics tests passed: tab isolation, redaction, no payloads, stop, limits, navigation, screenshot tab guard, attach failure.');
})().catch(e=>{console.error(e);process.exitCode=1;});
