const assert = require('node:assert/strict');
const path = require('node:path');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.CHROME_EXECUTABLE ? {executablePath:process.env.CHROME_EXECUTABLE} : {})});
  try {
    const page = await browser.newPage();
    await page.route('https://sample.test/**', route => route.fulfill({contentType:'text/html; charset=utf-8',body:'<title>示例标题</title><button id="sample">示例按钮</button>'}));
    await page.goto('https://sample.test/components/button?token=secret#private');
    await page.evaluate(() => {
      window.writes = [];
      window.chrome = {runtime:{id:'fixture',getURL:()=>'',onMessage:{addListener(){}},sendMessage:async()=>({ok:true})}};
      Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>window.writes.push(text)}});
    });
    await page.addScriptTag({path:path.join(__dirname,'../content.js')});
    await page.getByRole('button',{name:'选择控件',exact:true}).click();
    await page.locator('#sample').click();
    const toggle = page.getByRole('switch',{name:'附带来源链接',exact:true});
    assert(await toggle.isChecked());
    const preview = () => page.locator('[data-ref="preview"]').textContent();
    const initial = await preview();
    assert(initial.startsWith('# 组件采样'));
    for(const obsolete of ['目标位置','目标网址','仅做增量','默认新建','仅新增组件','已移除账号密码']) assert(!initial.includes(obsolete));
    await toggle.focus(); await page.keyboard.press('Space'); assert(!(await toggle.isChecked()));
    await page.keyboard.press('Space'); assert(await toggle.isChecked());
    await page.locator('.cs-preview summary').click();
    await page.setViewportSize({width:390,height:844});
    const box = await page.locator('.cs-detail').boundingBox(); assert(box.x >= 0 && box.x + box.width <= 390);
    const overflow = await page.locator('[data-ref="preview"]').evaluate(el=>({width:el.clientWidth,scroll:el.scrollWidth}));
    assert(overflow.scroll <= overflow.width + 1);
    await page.screenshot({path:path.join(__dirname,'source-preview-narrow.png')});
    await page.setViewportSize({width:1200,height:900});
    await page.screenshot({path:path.join(__dirname,'source-preview-desktop.png')});
    assert(initial.includes('来源链接：<https://sample.test/components/button>'));
    assert(initial.includes('页面标题："示例标题"'));
    assert(/采样时间：\d{4}-/.test(initial));
    assert(!initial.includes('token=secret') && !initial.includes('#private'));
    await page.getByRole('button',{name:'复制给 AI',exact:true}).click();
    await page.waitForFunction(()=>window.writes.length===1);
    assert.equal(await page.evaluate(()=>window.writes[0]),initial);
    await toggle.uncheck();
    const without = await preview();
    assert(!without.includes('## 来源') && !without.includes('https://sample.test/components/button'));
    await page.getByRole('button',{name:'复制给 AI',exact:true}).click();
    await page.waitForFunction(()=>window.writes.length===2);
    assert.equal(await page.evaluate(()=>window.writes[1]),without);
    await toggle.check();
    assert.equal(await preview(),initial);
    await page.evaluate(()=>history.pushState({},'', '/changed?email=private#route'));
    assert.equal(await preview(),initial);
    await page.getByRole('button',{name:'重新采样',exact:true}).click();
    assert((await preview()).includes('来源链接：<https://sample.test/changed>'));
    await page.getByRole('button',{name:'Figma',exact:true}).click();
    assert(await toggle.isDisabled());
    assert((await page.locator('[data-ref="source-note"]').textContent()).includes('Figma 图层不附带'));
    await page.getByRole('button',{name:'AI markdown',exact:true}).click();
    assert(await toggle.isChecked() && await toggle.isEnabled());
    await page.getByRole('button',{name:'问题反馈',exact:true}).click();
    await page.getByRole('button',{name:'反馈给天才潇洒的开发',exact:true}).click();
    assert((await page.locator('[data-ref="status"]').textContent()).includes('请先填写'));
    await page.locator('[data-ref="problem"]').fill('切换店铺后数据未更新');
    await page.locator('[data-ref="expected"]').fill('应显示当前店铺数据');
    await page.locator('[data-ref="steps"]').fill('1. 切换店铺');
    await page.evaluate(()=>{document.querySelector('#sample').setAttribute('data-testid','sales-card');});
    await page.getByRole('button',{name:'重新采样',exact:true}).click();
    let report = await preview();
    assert(report.startsWith('# 前端问题反馈') && report.includes('sales-card'));
    assert(report.includes('应显示当前店铺数据') && !report.includes('## 详细样式'));
    await page.getByRole('switch',{name:'附带详细样式'}).check();
    assert((await preview()).includes('## 详细样式'));
    await page.getByRole('switch',{name:'附带详细样式'}).uncheck();
    await page.getByRole('button',{name:'退出',exact:true}).click();
    assert(await page.getByRole('alertdialog').isVisible());
    await page.screenshot({path:path.join(__dirname,'floating-confirm.png')});
    await page.getByRole('button',{name:'继续填写',exact:true}).click();
    assert(!(await page.getByRole('alertdialog').isVisible()));
    assert(await page.locator('.cs-detail').isVisible());
    await page.getByRole('button',{name:'重新选择',exact:true}).click();
    await page.locator('#sample').click();
    assert.equal(await page.locator('[data-ref="problem"]').inputValue(),'切换店铺后数据未更新');
    await page.getByRole('button',{name:'组件采样',exact:true}).click();
    assert((await preview()).startsWith('# 组件采样'));
    await page.getByRole('button',{name:'问题反馈',exact:true}).click();
    report=await preview();
    await page.getByRole('button',{name:'反馈给天才潇洒的开发',exact:true}).click();
    await page.waitForFunction(()=>window.writes.length===3);
    assert.equal(await page.evaluate(()=>window.writes[2]),report);
    assert((await page.locator('.cs-confetti-particle').count())>0);
    await page.locator('.cs-detail').evaluate(el=>{el.scrollTop=0;});
    await page.screenshot({path:path.join(__dirname,'feedback-desktop.png')});
    await page.setViewportSize({width:390,height:844});
    const feedbackBox=await page.locator('.cs-detail').boundingBox();assert(feedbackBox.x>=0&&feedbackBox.x+feedbackBox.width<=390);
    await page.screenshot({path:path.join(__dirname,'feedback-narrow.png')});
    await page.getByRole('button',{name:'退出',exact:true}).click();
    assert(!(await page.locator('.cs-detail').isVisible()));
    await page.setViewportSize({width:1280,height:900});
    await page.evaluate(()=>window.__componentSampler.start());
    await page.getByRole('button',{name:'选择控件',exact:true}).click();await page.locator('#sample').click();
    await page.getByRole('button',{name:'退出',exact:true}).click();
    await page.getByRole('button',{name:'退出面板',exact:true}).click();assert(!(await page.locator('.cs-detail').isVisible()));
    console.log('Feedback checks passed: required problem, markers, optional CSS, retained draft, exit warning, copy equality, mode switching, narrow layout.');
    console.log('Source link checks passed: default, sanitized URL, title/time, preview/copy equality, toggle, snapshot, recapture, Figma scope.');
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
